FROM apache/airflow:2.10.5
COPY requirements.txt /

USER root

RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt

